# fly.toml app configuration file generated for skybridge on 2023-05-12T22:53:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bearnaiskybridge"
primary_region = "atl"

[build]
image = "videah/skybridge:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  SKYBRIDGE_BASEURL = "bearnaiskybridge.fly.dev"
  SKYBRIDGE_SHOW_INDEX = true
  FLY_SWAP = true
  SKYBRIDGE_SECRET='451865' #you need to fill it, I taped random numbers and it worked
  SKYBRIDGE_REQUIRE_AUTH_PASSWORD = true
  SKYBRIDGE_AUTH_PASSWORD = '451865' #if above is true, it will be asked when you'll try to log in to you bsky account in the app
  SKYBRIDGE_ALLOW_BACKFILL = true

[mounts]
  source="skybridge_data"
  destination="/app/database"

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/v2/instance"

[http_service.concurrency]
  type = "requests"
  hard_limit = 999999
  soft_limit = 9999

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
